--perfomance Queries set 3
-- 1.Write a SQL query to calculate total votes Got BJP in Bihar State in 1996?
CREATE OR REPLACE FUNCTION BIHAR_VOT_1996
RETURN VARCHAR
IS
BJP_VOT NUMBER;
BEGIN
SELECT SUM(TOTVOTPOLL) INTO BJP_VOT FROM ELECTION
WHERE ST_NAME = 'Bihar' AND YEAR = 1996;
RETURN 'Total Goa Votes for BJP in the year of 1996 : '||BJP_VOT;
END;

SELECT BIHAR_VOT_1996() FROM DUAL;

-- 2.Write a SQL query to display the BJP Candidates list in descending order?

CREATE OR REPLACE PROCEDURE BJP_CAND
IS
TYPE NAME_TYPE IS TABLE OF VARCHAR(100);
BJP_CAND_NAME NAME_TYPE;
BEGIN
SELECT DISTINCT(CAND_NAME) BULK COLLECT INTO BJP_CAND_NAME
FROM ELECTION 
WHERE PARTYABBRE = 'BJP'
ORDER BY CAND_NAME DESC;
FOR IDX IN 1..BJP_CAND_NAME.COUNT
LOOP
DBMS_OUTPUT.PUT_LINE(BJP_CAND_NAME(IDX));
END LOOP;
END;

BEGIN
BJP_CAND();
END;



-- 3. Find how many times congress gets above 50% vote in Bihar state?
 

SELECT PC_NAME,COUNT(TOTVOTPOLL) FROM ELECTION WHERE ST_NAME = 'Bihar'
AND PARTYABBRE = 'IND' GROUP BY PC_NAME HAVING ROUND(SUM(TOTVOTPOLL)/SUM(ELECTORS)*100,0) > 10;

 
--4. Find the Sikkim Candidate list each year?

CREATE OR REPLACE PROCEDURE SIK_CAND_YEAR
IS
TYPE NAME_TYPE IS TABLE OF VARCHAR(100);
TYPE COUNT_TYPE IS TABLE OF NUMBER;
ELECTION_YEAR COUNT_TYPE;
CD_NAME NAME_TYPE;
BEGIN
SELECT YEAR,CAND_NAME BULK COLLECT
INTO ELECTION_YEAR,CD_NAME 
FROM ELECTION 
WHERE ST_NAME = 'Sikkim'
ORDER BY YEAR;
FOR IDX IN 1..ELECTION_YEAR.COUNT
LOOP
 DBMS_OUTPUT.PUT_LINE(ELECTION_YEAR(IDX)||' '||CD_NAME(IDX));
END LOOP;
END;

BEGIN
SIK_CAND_YEAR();
END;

--5. Find total male candidates who participated in the election?
 
CREATE OR REPLACE FUNCTION MALE_CAND
RETURN VARCHAR
IS
MALE_CAND_COUNT NUMBER;
BEGIN
SELECT COUNT(CAND_NAME) INTO MALE_CAND_COUNT 
FROM ELECTION 
WHERE CAND_SEX = 'M';
RETURN 'Total Male Candidates : '||MALE_CAND_COUNT;
END;

SELECT MALE_CAND() FROM DUAL;
