--perfomance Queries set 2


-- 1. Display the BJP candidate list participated at state Andaman & Nicobar Islands in the year 1984?
  
  CREATE OR REPLACE PROCEDURE BJPCAND_ANI_1984
  IS
  C_NAME VARCHAR(32);
  BEGIN
  SELECT CAND_NAME INTO C_NAME
  FROM ELECTION 
  WHERE PARTYABBRE = 'BJP' AND 
  ST_NAME = 'Andaman & Nicobar Islands' AND YEAR = 2014;
  DBMS_OUTPUT.PUT_LINE('ANI Candidates are : '||C_NAME);
  END;

   
  BEGIN
  BJPCAND_ANI_1984();
  END;


 
 --2.How many Male Candidates participated in elections in each state?

CREATE OR REPLACE PROCEDURE MALE_CAND_STATE
IS
TYPE COUNT_TYPE IS TABLE OF NUMBER;
TYPE NAME_TYPE IS TABLE OF VARCHAR(100);
STATE NAME_TYPE;
CAND_COUNT COUNT_TYPE;
BEGIN
SELECT ST_NAME,COUNT(CAND_NAME) BULK COLLECT INTO STATE,CAND_COUNT 
FROM ELECTION 
WHERE CAND_SEX = 'M' 
GROUP BY ST_NAME;
FOR IDX IN 1..STATE.COUNT
LOOP
DBMS_OUTPUT.PUT_LINE(STATE(IDX)||'  '||CAND_COUNT(IDX));
END LOOP;
END;

   
BEGIN
MALE_CAND_STATE();
END;

--3. Display the Party name in descending order?

CREATE OR REPLACE PROCEDURE PARTIES
IS
TYPE NAME_TYPE IS TABLE OF VARCHAR(100);
PARTY NAME_TYPE;
BEGIN
SELECT DISTINCT(PARTYNAME) BULK COLLECT INTO PARTY 
FROM ELECTION 
ORDER BY PARTYNAME DESC;
FOR IDX IN 1..PARTY.COUNT
LOOP
DBMS_OUTPUT.PUT_LINE(PARTY(IDX));
END LOOP;
END;

BEGIN
PARTIES();
END;

 --4. Find how many Candidates participated in the year West Bengal 1988? 

CREATE OR REPLACE FUNCTION WB_CAND_1988
RETURN VARCHAR
IS
WB_CAND NUMBER;
BEGIN
SELECT COUNT(CAND_NAME) INTO WB_CAND 
FROM ELECTION
WHERE ST_NAME = 'West Bengal'
AND YEAR = 2014;
RETURN 'Total Candidates of West Bengal in the Year 1988 : '||WB_CAND;
END;
    

SELECT WB_CAND_1988() FROM DUAL;


--5.  Display the Tamilnadu Candidate list each year?

CREATE OR REPLACE PROCEDURE PARTIES
IS
TYPE NAME_TYPE IS TABLE OF VARCHAR(100);
TYPE COUNT_TYPE IS TABLE OF NUMBER;
ELECTION_YEAR COUNT_TYPE;
C_NAME NAME_TYPE;
BEGIN
SELECT YEAR,CAND_NAME BULK COLLECT 
INTO ELECTION_YEAR,C_NAME
FROM ELECTION 
WHERE ST_NAME = 'Tamil Nadu' 
ORDER BY YEAR;
FOR IDX IN 1..ELECTION_YEAR.COUNT
LOOP
DBMS_OUTPUT.PUT_LINE(ELECTION_YEAR(IDX)||' '||C_NAME(IDX));
END LOOP;
END;

BEGIN
PARTIES();
END;



