select CAND_NAME FROM Election WHERE ST_NAME = 'Andaman & Nicobar Islands' and Partyabbre = 'BJP' and year = 1988; 

SELECT COUNT(CAND_NAME), ST_NAME FROM ELECTION WHERE CAND_SEX = 'M' GROUP BY ST_NAME;

SELECT PARTYNAME FROM ELECTION GROUP BY PARTYNAME ORDER BY PARTYNAME DESC;

SELECT COUNT(CAND_NAME) FROM ELECTION WHERE ST_NAME = 'West Bengal' and year = 1988;


