select count(CAND_NAME), ST_NAME FROM ELECTION WHERE YEAR = 2004 GROUP BY ST_NAME;


SELECT COUNT(CAND_NAME), YEAR FROM ELECTION WHERE CAND_SEX = 'F' GROUP BY YEAR;


SELECT COUNT(CAND_NAME) FROM ELECTION WHERE ST_NAME = 'WEST BENGAL' AND YEAR = 2014;

SELECT COUNT(CAND_NAME) , ST_NAME , YEAR  FROM ELECTION