select count(CAND_NAME) as Total_Candidates, ST_NAME FROM ELECTION WHERE YEAR = 2004 GROUP BY ST_NAME;


SELECT COUNT(CAND_NAME) as Female_Candidates, YEAR FROM ELECTION WHERE CAND_SEX = 'F' GROUP BY YEAR order by year asc;


SELECT COUNT(CAND_NAME) as Total_Candidates FROM ELECTION WHERE ST_NAME = 'West Bengal' AND YEAR = 2014;

SELECT COUNT(CAND_NAME) , ST_NAME , YEAR  FROM ELECTION group by ST_NAME , YEAR ORDER BY ST_NAME , YEAR;

SELECT PARTYNAME FROM ELECTION WHERE ST_NAME = 'Uttar Pradesh' and YEAR = 2014 group by partyname order by SUM(TOTVOTPOLL) DESC FETCH FIRST 5 ROWS ONLY;

SELECT ST_NAME , SUM(TOTVOTPOLL) AS VOTES FROM ELECTION WHERE YEAR = 1987 AND PARTYNAME = '	
Bharatiya Janata Party' GROUP BY ST_NAME;


select CAND_NAME FROM Election WHERE ST_NAME = 'Andaman & Nicobar Islands' and Partyabbre = 'BJP' and year = 1984;
