select count(CAND_NAME), ST_NAME FROM ELECTION WHERE YEAR = 2004 GROUP BY ST_NAME;


SELECT COUNT(CAND_NAME), YEAR FROM ELECTION WHERE CAND_SEX = 'F' GROUP BY YEAR;
 
SELECT COUNT(CAND_NAME) FROM ELECTION WHERE ST_NAME = 'WEST BENGAL' AND YEAR = 2014;




SELECT COUNT(CAND_NAME) , ST_NAME , YEAR  FROM ELECTION group by ST_NAME , YEAR;
 
select count(CAND_NAME) as Total_Candidates, ST_NAME FROM ELECTION WHERE YEAR = 2004 GROUP BY ST_NAME;
 
 
SELECT COUNT(CAND_NAME) as Female_Candidates, YEAR FROM ELECTION WHERE CAND_SEX = 'F' GROUP BY YEAR order by year asc;
 
 
SELECT COUNT(CAND_NAME) as Total_Candidates FROM ELECTION WHERE ST_NAME = 'West Bengal' AND YEAR = 2014;
 
SELECT COUNT(CAND_NAME) , ST_NAME , YEAR  FROM ELECTION group by ST_NAME , YEAR ORDER BY ST_NAME , YEAR;
 
SELECT ST_NAME ,SUM(TOTVOTPOLL) AS VOTES FROM ELECTION WHERE YEAR = 1987 AND PARTYNAME = 'BJP';
 
 
SELECT PARTYNAME FROM ELECTION WHERE ST_NAME = 'Uttar Pradesh' and YEAR = 2014 group by partyname order by SUM(TOTVOTPOLL) DESC FETCH FIRST 5 ROWS ONLY;
 
 
 
SELECT ST_NAME ,SUM(TOTVOTPOLL) AS VOTES FROM ELECTION WHERE YEAR = 1987 AND PARTYNAME = 'BJP';

select sum(TOTVOTPOLL)  from ELECTION where year=1987
and ST_NAME='Andhra Pradesh' and PARTYABBRE='BJP';


SELECT ST_NAME ,sum(TOTVOTPOLL) FROM ELECTION WHERE YEAR = 1987 AND PARTYABBRE = 'BJP' 
group by st_name
 order by sum(TOTVOTPOLL);

select round(sum(TOTVOTPOLL)/sum(ELECTORS)*100,2)  as percentage from election where year=2004 and st_name='Goa' and partyabbre='BJP';
select * from election;

select count(*)  from election
where round(sum(select TOTVOTPOLL from ELECTION where PARTYABBRE='BJP')/sum(select ELECTORS from ELECTION where PARTYABBRE='BJP')*100,2)>50 
and PARTYABBRE='BJP