-- Find the total candidates who participated in the election in each state in the year 2004?
CREATE OR REPLACE PROCEDURE Find_Cand_Total
IS
  TYPE Name1t IS TABLE OF VARCHAR(60);
  TYPE CAND_C IS TABLE OF NUMBER;
  state NAME1t;
  countofs CAND_C;
BEGIN
  SELECT
     ST_NAME,
     COUNT(CAND_NAME) BULK COLLECT INTO
    state, countofs  FROM ELECTION WHERE YEAR = 2004 GROUP BY ST_NAME;
 FOR i IN 1..state.COUNT LOOP
     DBMS_OUTPUT.PUT_LINE(state(i)||'  '||countofs(i));
 END LOOP;
END;
/

BEGIN
 Find_Cand_Total();
END;
/



--Find the total female candidates participating each year?
CREATE OR REPLACE PROCEDURE FIND_FEMALE_CAND
IS
  TYPE CAND_C IS TABLE OF NUMBER;
  FEMALE_COUNT CAND_C;
  E_YEAR CAND_C;
BEGIN
  SELECT COUNT(CAND_SEX), YEAR
  BULK COLLECT INTO FEMALE_COUNT,E_YEAR
  FROM ELECTION WHERE CAND_SEX = 'F' GROUP BY YEAR;
 FOR i IN 1..FEMALE_COUNT.COUNT LOOP
     DBMS_OUTPUT.PUT_LINE(E_YEAR(i)||'  '||FEMALE_COUNT(i));
 END LOOP;
END;
/


BEGIN
  FIND_FEMALE_CAND();
END;
/

--3.find the total candidates who participated in West Bengal state in the year 2014
CREATE OR REPLACE PROCEDURE FEMALE_CAND_YEAR
IS
  TYPE CAND_COUNT IS TABLE OF NUMBER;
  female_cand CAND_COUNT;
  e_year CAND_COUNT;
BEGIN
  SELECT COUNT(CAND_SEX), YEAR
  BULK COLLECT INTO female_cand,e_year FROM ELECTION
  WHERE  CAND_SEX = 'F'
  GROUP BY YEAR;
 FOR i IN 1..female_cand.COUNT LOOP
     DBMS_OUTPUT.PUT_LINE(e_year(i)||'  '||female_cand(i));
 END LOOP;
END;
/

begin
FEMALE_CAND_YEAR();
END;
/

--Find the total candidates who participated in the election at each state in each year
CREATE OR REPLACE PROCEDURE CAND_EACH_YEAR
IS
  TYPE CTypea IS TABLE OF NUMBER;
  TYPE NTypea IS TABLE OF VARCHAR(100);
  state NTypea;
  e_year CTypea;
  cand_c CTypea;
BEGIN
  SELECT ST_NAME, YEAR, COUNT(CAND_NAME) BULK COLLECT INTO state, e_year, cand_c FROM ELECTION
  GROUP BY YEAR, ST_NAME ;
  FOR i IN 1..STATE.COUNT LOOP
     DBMS_OUTPUT.PUT_LINE(state(i)||'  '||e_year(i)||' '||cand_c(i));
  END LOOP;
END;
/

BEGIN
CAND_EACH_YEAR();
END;
/

--5. What are the top 5 parties that got the most votes in Uttar Pradesh in the year 2014
CREATE OR REPLACE PROCEDURE QUES_5_TOP5
IS
PARTIES VARCHAR(100);
  CURSOR C1
  IS
     SELECT
        DISTINCT PARTYNAME FROM  ELECTION WHERE
        ST_NAME = 'Uttar Pradesh' AND ROWNUM <= 5 AND YEAR = 2014 GROUP BY PARTYNAME
  ORDER BY SUM(TOTVOTPOLL) DESC FETCH FIRST 5 ROWS ONLY;
BEGIN
     OPEN C1;
     LOOP
        FETCH C1 INTO PARTIES;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(PARTIES);
     END LOOP;
     CLOSE C1;
END;
/

BEGIN
QUES_5_TOP5();
END;
/


--6.Find total votes BJP got In each state in the year 1987?
CREATE OR REPLACE PROCEDURE VOTESOF_BJP_1987
IS
  TYPE CTYPE IS TABLE OF NUMBER;
  TYPE NTYPE IS TABLE OF VARCHAR(100);
  STATE NTYPE;
  VOTES_IN_STATES CTYPE;
BEGIN
  SELECT
     ST_NAME, SUM(TOTVOTPOLL) BULK COLLECT INTO STATE, VOTES_IN_STATES
  FROM ELECTION
  WHERE PARTYABBRE = 'BJP'
  AND YEAR = 1987  GROUP BY ST_NAME;
  FOR i IN 1..STATE.COUNT LOOP
     DBMS_OUTPUT.PUT_LINE(STATE(i)||'  '||VOTES_IN_STATES(i));
  END LOOP;
END;
/


BEGIN
VOTESOF_BJP_1987();
END;
/

--7.Find the Total votes BJP Got in state 'andhra pradesh' in the year 1987

CREATE OR REPLACE PROCEDURE BJP_IN_AP_1987
IS
TOT_VOTES NUMBER;
BEGIN
SELECT COUNT(TOTVOTPOLL) INTO TOT_VOTES FROM ELECTION 
WHERE ST_NAME = 'Andhra Pradesh' and year = 1987;
DBMS_OUTPUT.PUT_LINE(TOT_VOTES);
END;
/

BEGIN
BJP_IN_AP_1987();
END;
/

--8. Find the Total vote percentage of BJP get in goa state in the year 2003
CREATE OR REPLACE PROCEDURE VOT_PERCENT_BJP_GOA
IS
PERCENT NUMBER;
BEGIN
SELECT SUM((TOTVOTPOLL))/SUM((ELECTORS)) * 100 INTO PERCENT FROM ELECTION 
WHERE ST_NAME = 'Goa' and Year = 2004 and PARTYABBRE = 'BJP';
DBMS_OUTPUT.PUT_LINE(ROUND(PERCENT,2));
END;
/
--IN 2004 ONLY BJP PARTICIPATED IN ELECTION

BEGIN
VOT_PERCENT_BJP_GOA();
END;
/

--9. How many times has BJP gotten an Above 50% vote?
CREATE OR REPLACE PROCEDURE BJP_ABV50
IS
PERCENT NUMBER;
BEGIN
SELECT count(*) INTO PERCENT FROM ELECTION 
WHERE PARTYABBRE = 'BJP' and (TOTVOTPOLL)/(ELECTORS) * 100 > 50;
DBMS_OUTPUT.PUT_LINE(PERCENT);
END;
/

BEGIN
BJP_ABV50();
END;
/

--10. what is the state list the BJP gets below 75% vote?
CREATE OR REPLACE PROCEDURE STATE_LIST_BW75
IS
TYPE NTYPE IS TABLE OF VARCHAR(100);
VOTES_OF_STATES NTYPE;
BEGIN
SELECT ST_NAME BULK COLLECT INTO VOTES_OF_STATES FROM ELECTION 
WHERE PARTYABBRE = 'BJP' AND (TOTVOTPOLL)/(ELECTORS) * 100 < 75 GROUP BY ST_NAME; 
FOR i IN 1..VOTES_OF_STATES.COUNT LOOP
DBMS_OUTPUT.PUT_LINE(VOTES_OF_STATES(i));
END LOOP;
END;
/


BEGIN
STATE_LIST_BW75();
END;
/