SELECT 
    ELECTION_ID, 
    ELECTION_DATE,
    RESULT_DATE
FROM 
    ELECTION;
----------------------------------------------------------
SELECT * FROM ADDRESS;

SELECT 
    V.FIRST_NAME,V.DATE_OF_BIRTH,V.PASSWORD,A.DISTRICT_ID
FROM
    VOTER V ,ADDRESS A
WHERE 
    V.AADHAAR = A.VAADHAAR AND A.ZIP_CODE = 522433;
----------------------------------------------------------------        
CREATE OR REPLACE PROCEDURE LOGIN(V_USER_ID VARCHAR,V_PASSWORD VARCHAR)
IS
    U_USER_ID VARCHAR(32);
    U_PASSWORD VARCHAR(32);
    U_CAND VARCHAR(100);
BEGIN
    SELECT 
        AADHAAR,
        PASSWORD 
    INTO
        U_USER_ID,
        U_PASSWORD 
    FROM 
        VOTER 
    WHERE 
        AADHAAR = V_USER_ID;   
    IF V_USER_ID = U_USER_ID AND  V_PASSWORD = U_PASSWORD THEN
        DBMS_OUTPUT.PUT_LINE('LOGGEDIN');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR');   
    END IF;
END;
/

SELECT * FROM VOTER;

BEGIN
   LOGIN(' 8168 4719 1549 ',' sAry4I4 ');
END;
/

CREATE OR REPLACE PROCEDURE ELECTION_1
IS
    V_ELECTION_ID VARCHAR(32);
    BEGIN
        SELECT 
        ELECTION_ID 
    INTO 
        V_ELECTION_ID 
    FROM 
        ELECTION 
    WHERE 
        ELECTION_TYPE = 'MLA';
    DBMS_OUTPUT.PUT_LINE(V_ELECTION_ID);
END;
/

BEGIN
    ELECTION_2();
END;
/


CREATE OR REPLACE PROCEDURE ELECTION_2
IS
    V_ELECTION_ID VARCHAR(32);
    V_ELECTION_DATE VARCHAR(32);
BEGIN
    SELECT 
        ELECTION_ID,
        ELECTION_DATE 
    INTO 
        V_ELECTION_ID,
        V_ELECTION_DATE 
    FROM 
        ELECTION 
    WHERE 
        ELECTION_TYPE = 'MLA';
    DBMS_OUTPUT.PUT_LINE(V_ELECTION_ID);
END;
/

END;
SELECT 
    * 
FROM 
    ELECTION;

SELECT 
    ELECTION_ID 
FROM 
    ELECTION 
WHERE 
    ELECTION_TYPE = 'MLA';

SELECT 
    ELECTION_ID,
    ELECTION_TYPE 
FROM 
    ELECTION;

SELECT 
    ELECTION_ID,
    RESULT_DATE 
FROM 
    ELECTION;

SELECT 
    ELECTION_ID,
    ELECTION_DATE,
    RESULT_DATE 
FROM 
    ELECTION;

SELECT 
    ELECTION_ID,
    ELECTION_DATE,
    RESULT_DATE
FROM 
    ELECTION 
WHERE 
    ELECTION_TYPE = 'MLA';

SELECT 
    ELECTION_ID,
    ELECTION_DATE,
    RESULT_DATE 
FROM 
    ELECTION 
WHERE 
    ELECTION_TYPE = 'MP';

SELECT 
    ELECTION_TYPE 
FROM 
    ELECTION;

SELECT 
    ELECTION_TYPE 
FROM 
    ELECTION 
WHERE 
    ELECTION_DATE = '08-MAR-22';
