DECLARE
  TYPE V_AADHAAR IS TABLE OF VARCHAR(32);
  VO_AADHAAR V_AADHAAR;
  VO_FIRST_NAME V_AADHAAR; 
BEGIN
  SELECT 
    AADHAAR,
    FIRST_NAME 
  BULK COLLECT INTO 
    VO_AADHAAR,
    VO_FIRST_NAME 
  FROM 
    VOTER;
  FOR IDX IN 1..VO_AADHAAR.COUNT LOOP
    DBMS_OUTPUT.PUT_LINE(VO_AADHAAR(IDX)|| '  '||FIRSTNAME(IDX));
  END LOOP;
END;
/


DECLARE
    CURSOR EXP_CUR 
    IS
      SELECT 
      FIRST_NAME,
      LAST_NAME 
    FROM 
      VOTER;
    TYPE V_FNAME IS TABLE OF VARCHAR(32);
    FNAME V_FNAME;
    LNAME V_FNAME;
BEGIN
  OPEN EXP_CUR;
    FETCH EXP_CUR BULK COLLECT INTO FNAME,LNAME LIMIT 10;
    FOR IDX IN FNAME.FIRST..FNAME.LAST
    LOOP
      DBMS_OUTPUT.PUT_LINE(IDX|| '  '||FNAME(IDX)||'   '||LNAME(IDX));
    END LOOP;
  CLOSE EXP_CUR;
END;
/
-------- for all(upperbound and lowerbound)
CREATE TABLE USER_ID(VOTE_ID NUMBER);
CREATE SEQUENCE FORALL_SEQ INCREMENT BY 1 START WITH 21 ORDER;

DECLARE

   TYPE USER IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
   V_USER_ID USER;
BEGIN
  FOR I IN 1..5 
  LOOP
   V_USER_ID (I) := FORALL_SEQ.NEXTVAL;
   END LOOP;
   FORALL IDX IN 1..5
      INSERT INTO USER_ID(VOTE_ID) VALUES(V_USER_ID(IDX));
  SELECT VOTE_ID BULK COLLECT INTO V_USER_ID FROM USER_ID;
  FOR IDX IN V_USER_ID.FIRST..V_USER_ID.LAST 
  LOOP
   DBMS_OUTPUT.PUT_LINE(IDX||'  '||V_USER_ID(IDX));
  END LOOP;
END;
/
------------------FOR ALL(INDICES OF)

CREATE TABLE SERIALNO(SERIAL_NO NUMBER);


DECLARE

   TYPE MY_TABLE IS TABLE OF NUMBER;
   V_USER_ID MY_TABLE := MY_TABLE(1,2,3,4,5,6,7,8);
BEGIN
  
    V_USER_ID.DELETE(2,5);
    FORALL IDX IN INDICES OF V_USER_ID
    INSERT INTO SERIALNO(SERIAL_NO) VALUES(V_USER_ID(IDX));
    SELECT SERIAL_NO BULK COLLECT INTO V_USER_ID FROM SERIALNO;
  FOR I IN V_USER_ID.FIRST..V_USER_ID.LAST 
   LOOP
   DBMS_OUTPUT.PUT_LINE(I||'  '||V_USER_ID(I));
  END LOOP;
END;
/
------------------------------>      FOR ALL(VALUES OF)
DROP TABLE SERIALNO;
CREATE TABLE SERIALNO(SERIAL_NO NUMBER);
DECLARE

   TYPE MY_TABLE IS TABLE OF NUMBER;
   V_USER_ID MY_TABLE := MY_TABLE(23,45,67,16,76,90,37,12);
   TYPE MY_ARRAY IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER;
   INDEX_COL MY_ARRAY;
  
BEGIN
  
    INDEX_COL (6) := 2;
    INDEX_COL (12) := 4;
    INDEX_COL (15) := 6;
    INDEX_COL (20) := 8;
    --FORALL IDX IN VALUES OF INDEX_COL
   -- INSERT INTO SERIALNO VALUES(V_USER_ID(IDX));
    --SELECT SERIAL_NO BULK COLLECT INTO V_USER_ID FROM SERIALNO;
    --DBMS_OUTPUT.PUT_LINE(INDEX_COL.LAST);
  FOR I IN INDEX_COL.FIRST..INDEX_COL.LAST
   LOOP
   DBMS_OUTPUT.PUT_LINE(INDEX_COL(I));
  END LOOP;
END;
/

-----> 










