--1. Display the BJP candidate list participated at state Andaman & Nicobar Islands in the year 1984?

CREATE OR REPLACE PROCEDURE ANI_1984
IS
 cand_name VARCHAR(32);
BEGIN
 SELECT
   CAND_NAME
 INTO  cand_name
 FROM ELECTION WHERE PARTYABBRE = 'BJP'
 AND ST_NAME = 'Andaman & Nicobar Islands' AND YEAR = 2014;
 DBMS_OUTPUT.PUT_LINE(cand_name);
END;
/

begin
ANI_1984();
END;
/

--2. How many Male Candidates participated in elections in each state?
CREATE OR REPLACE PROCEDURE MALE_CAND_1
IS
  TYPE COUNT_TYPE IS TABLE OF NUMBER;
  TYPE NAME_TYPE IS TABLE OF VARCHAR(100);
  STATES NAME_TYPE;
  CAND_C COUNT_TYPE;
BEGIN
 SELECT
   ST_NAME,COUNT(CAND_NAME) BULK COLLECT INTO STATES,CAND_C
 FROM  ELECTION
 WHERE CAND_SEX = 'M' GROUP BY ST_NAME;
 FOR i IN 1..STATES.COUNT
 LOOP
  DBMS_OUTPUT.PUT_LINE(STATES(i)||'  '||CAND_C(i));
 END LOOP;
END;
/

BEGIN
MALE_CAND_1();
END;
/

--3. Display the Party name in descending order?
CREATE OR REPLACE PROCEDURE PARTIES
IS
 TYPE NTYPE IS TABLE OF VARCHAR(100);
 PARTIES NTYPE;
BEGIN
 SELECT
 DISTINCT
   (PARTYNAME)
 BULK
   COLLECT
 INTO
   PARTIES
 FROM  ELECTION ORDER BY PARTYNAME DESC;
 FOR i IN 1..PARTIES.COUNT
 LOOP
  DBMS_OUTPUT.PUT_LINE(PARTIES(i));
 END LOOP;
END;
/

BEGIN
PARTIES();
END;
/

--4. Find how many Candidates participated in the year West Bengal 1988?
CREATE OR REPLACE PROCEDURE CAND_PART
IS
COUNT_C NUMBER;
BEGIN
SELECT COUNT(CAND_NAME) INTO COUNT_C 
FROM ELECTION WHERE ST_NAME = 'West Bengal' and year = 1988;
DBMS_OUTPUT.PUT_LINE(COUNT_C);
END;
/

BEGIN
CAND_PART();
END;
/


--5. Display the Tamilnadu Candidate list each year?
CREATE OR REPLACE PROCEDURE PARTIES12
IS
 TYPE NAME_TYPE IS TABLE OF VARCHAR(100);
 TYPE COUNT_TYPE IS TABLE OF NUMBER;
 e_year COUNT_TYPE;
 c_name NAME_TYPE;
BEGIN
 SELECT
   YEAR,CAND_NAME
 BULK
   COLLECT
 INTO
   e_year,c_name
 FROM ELECTION WHERE ST_NAME = 'Tamil Nadu' ORDER BY YEAR;
 FOR i IN 1..e_year.COUNT
 LOOP
   DBMS_OUTPUT.PUT_LINE(e_year(i)||' '||c_name(i));
 END LOOP;
END;
/

BEGIN
PARTIES12();
END;
/

